version: '3.9'

services:
  redis:
    ports:
      - 6379:6379
  weather-bot:
    environment:
      REDIS_URL: 'redis'
      REDIS_PORT: 6379
      WEATHER_API_KEY:
      MINUTE_LIMIT: '60'
      TG_API_ID:
      TG_API_HASH:
      TG_API_KEY:
